version: '3.1'

services:
  db:
    image: mariadb:10.11.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  php:
    build: ./php
    ports:
        - 8091:80
    volumes:
      - ./../:/var/www/html
